using System;
using System.Collections.Generic;
using System.Text;
using ModelsRepository.Models.Profile;

namespace ModelsRepository.Models.HomeDetailApi
{
    public class ApiHomeDetails
    {
        public int HomeId { get; set; }
        public int ListingId { get; set; }
        public bool IsSpec { get; set; }
        public string Desc { get; set; }
        public int IsDescAutoGenerated { get; set; }
        public string Addr { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public int LotSft { get; set; }
        public string Status { get; set; }
        public string Thumb { get; set; }
        public bool IsTrackingNumber { get; set; }
        public int MktId { get; set; }
        public bool IsParentCommActive { get; set; }
        public bool IsBasic { get; set; }
        public double Lat { get; set; }
        public double Lng { get; set; }
        public ApiBuilder Builder { get; set; }
        public ApiBrand Brand { get; set; }
        public DateTime Time { get; set; }
        public List<ApiImage> Images { get; set; }
        public List<ApiImage> PlanImages { get; set; }
        public List<ApiVideo> Videos { get; set; }
        public List<ApiSummary> Summary { get; set; }
        public List<ApiSummary> PlanAmenities { get; set; }
        public List<ApiSummary> LivingAreas { get; set; }
        public List<ApiSummary> IntMedia { get; set; }
        public List<ApiInteractiveMedia> CustomAmenities { get; set; }
        public List<ApiHomeOption> HomeOptions { get; set; }
        public List<ApiSchoolDistrict> Schools { get; set; }
        public List<ApiAmenity> Amenities { get; set; }
        public List<ApiUtility> Utilities { get; set; }
        public bool IsActive { get; set; }
        public DateTime LastModified { get; set; }
        public List<ApiSalesAgent> Agents { get; set;}
        public List<ApiBrochure> Brochures { get; set; }
        public bool OutOfCommunityFlag { get; set; }
        public bool IsLandExcluded { get; set; }
        public  string Server { get; set;}
        public List<ApiFeesAndRates> FeesAndRates { get; set; }


    }
}
